server:
  port: 8080

spring:
  application:
    name: core-service

  # Database Connection (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/flowfin_db
    username: flowfin_user
    password: flowfin_password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true # Автоматически пометит существующую БД как baseline, если в ней уже созданы таблицы
    baseline-version: 0
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Event Streaming (Apache Kafka)
  kafka:
    bootstrap-servers: localhost:9092
    
    # Конфигурация отправки сообщений (Producer)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

    # Конфигурация вычитывания сообщений (Consumer)
    consumer:
      group-id: core-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: "com.flowfin.core.event.DocumentIngestedEvent"
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "com.flowfin.core.event,com.flowfin.core.dto"

app:
  processing:
    timeout-seconds: 10
  chunking:
    max-chunk-size: 500
    overlap-size: 50
  qdrant:
    host: ${QDRANT_HOST:localhost}
    port: ${QDRANT_PORT:6334}
    collection-name: document_chunks
    vector-size: 384 # Standard size for miniature embedding models (e.g. all-MiniLM-L6-v2)
  kafka:
    topics:
      raw-documents: raw-documents-topic